import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from '@/component/Layout'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    <main className='flex items-center text-dark w-full min-h-screen'>
      <Layout>
        <div className='flex items-center justify-between w-full'></div>
      </Layout>
    </main>
    </>
  )
}
