import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/component/Layout";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/component/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/component/Icon";
import { useRouter } from "next/router";
import { ButtonContact, ButtonResume } from "@/component/Button";
import Transition from "@/component/Transition";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transition/>

      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="p-32 pt-0 xl:p-24 lg:p-16 md:p-12 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="Izaditya"
                className="w-full h-auto m-auto lg:inline-block lg:w-full"
                priority
                sizes="( max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-5xl  md:!text-4xl  sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/resume.pdf"
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  CV <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="adityaimam8@gmail.com"
                  className="relative group ml-4 text-lg font-medium capitalize text-dark dark:text-light md:text-base"
                >
                  Contact
                  <span
                    className={`h-[2px] inline-block bg-dark dark:bg-light absolute left-0 -bottom-0.5 group-hover:w-full transition-[width] ease duration-300 ${
                      router.asPath === "adityaimam8@gmail.com"
                        ? "w-full"
                        : "w-0"
                    }`}
                  ></span>
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
